defaults:
  - mppi: heijn_push
  - isaacgym: push

goal: [2.0, 2.0, 0.0]
render: true
n_steps: 5
nx: 6

actors: ['heijn', 'block', 'paper_obst1', 'paper_obst2', 'goal']
initial_actor_positions: [[0.0, 1.5, 0.05]]

hydra:
  searchpath:
    - pkg://conf