defaults:
  - mppi: anymal
  - isaacgym: push

goal: [2.0, 2.0]
render: true
n_steps: 1000
nx: 24 

actors: ['anymal', 'goal']
initial_actor_positions: [[0.0, 2.0, 1.2]]

hydra:
  searchpath:
    - pkg://conf