defaults:
  - mppi: heijn_reach
  - isaacgym: normal

goal: [2.0, 2.0, 0.0]
render: true
n_steps: 5
nx: 6

actors: ['heijn', 'wall', 'goal']
initial_actor_positions: [[0.0, 0.0, 0.05]]

hydra:
  searchpath:
    - pkg://conf